#!/bin/bash

#PBS -l nodes=1:ppn=4
#PBS -l vmem=29gb
#PBS -l walltime=1:00:00
#PBS -N app-cortex-mapping-stats
#PBS -V

#set -e

# copy license and export path for freesurfer
[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

# convert surfaces and generate appropriate summary statistic text files
time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/connectome_workbench:1.4.2b ./compute-stats.sh

# generate csv's for each statistic that can be useful in MLC analyses
time singularity exec -e docker://brainlife/freesurfer-stats:1.2 ./generateCSV.py

if [ -f ./parc-stats/aparc_STDEV.csv ]; then
	mkdir raw
	mv aparc-rois/ *.txt *.gii ./raw/
	echo "complete"
	exit 0
else
	echo "stats computations failed somewhere. please check logs and derivatives"
	exit 1
fi
