#!/bin/bash

#PBS -l nodes=1:ppn=1
#PBS -l vmem=8gb
#PBS -l walltime=5:30:00
#PBS -N app-cortex-mapping-stats
#PBS -V

set -e

aparc_to_use=`jq -r '.validator_csv' config.json`

[ ! -d ./parc-stats ] && mkdir -p ./parc-stats

# copy license and export path for freesurfer
[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

# scale measures if necessary
time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/connectome_workbench:1.4.2b ./scale-measures.sh

# compute statistics
time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer:7.2.0 ./compute-stats.sh

# generate csv's for each statistic that can be useful in MLC analyses
time singularity exec -e docker://brainlife/freesurfer-stats:1.2 ./generateCSV.py

if [ -f ./parc-stats/parc-stats/aparc.csv ]; then
	mkdir raw
	mv *.gii *.txt *.csv *.annot ./raw/
	cp ./parc-stats/parc-stats/${aparc_to_use}.csv ./parc-stats/parc-stats/cortex.csv
	echo "complete"
	exit 0
else
	echo "stats computations failed somewhere. please check logs and derivatives"
	exit 1
fi
